### ISSUE TITLE
代理服务器端口

### ISSUE THREAD

**Issue by ecol0408** [iMrDJAi/cordova-plugin-tun2socks-udp-associate#2]
这个不能传服务器端口吗，用户名和密码倒是可以重写

**Comment by iMrDJAi** [comment]
@ecol0408 If I understand what you're saying correctly, you can pass the server port within the server address string itself (`address:port`):
```js
window.tun2socks.start('127.0.0.1:1080').then(function(a) {
    console.log('Started tun2socks!')
}).catch(function (err) {
    console.log('Error ' + err)
})
```
And nope! authentication with username/password isn't supported.  
By the way you can only connect to a socks v5 server running on the device itself, due to some limitations only local addresses are supported (`127.0.0.1`, `localhost`...). Therefore you'll have to get your own custom socks v5 server for your app running on `localhost`, then forward its traffic to a remote socks v5, ssh or any type of proxy servers! and at this level you can use authentication.

**Comment by ecol0408** [comment]
ok thank you
